// import { APP_PREFIX_PATH } from 'constants/route.constant'
// import {
//     NAV_ITEM_TYPE_TITLE,
//     NAV_ITEM_TYPE_COLLAPSE,
//     NAV_ITEM_TYPE_ITEM,
// } from 'constants/navigation.constant'
// import { ADMIN, USER, VENDOR } from 'constants/roles.constant'

// const appsNavigationConfig = [
//     {
//         key: 'apps',
//         path: '',
//         title: 'Dashboard',
//         translateKey: 'nav.apps',
//         icon: 'apps',
//         type: NAV_ITEM_TYPE_TITLE,
//         authority: [ADMIN, USER, VENDOR],
//         subMenu: [
//             {
//                 key: 'apps.sales',
//                 path: '',
//                 title: 'Sales',
//                 translateKey: 'nav.appsSales.sales',
//                 icon: 'sales',
//                 type: NAV_ITEM_TYPE_COLLAPSE,
//                 authority: [ADMIN, USER],
//                 subMenu: [
//                     {
//                         key: 'appsSales.dashboard',
//                         path: `${APP_PREFIX_PATH}/sales/dashboard`,
//                         title: 'Dashboard',
//                         translateKey: 'nav.appsSales.dashboard',
//                         icon: '',
//                         type: NAV_ITEM_TYPE_ITEM,
//                         authority: [ADMIN, USER],
//                         subMenu: [],
//                     },
//                     {
//                         key: 'appsSales.categoryList',
//                         // path: `${APP_PREFIX_PATH}/sales/product-list`,
//                         path: `${APP_PREFIX_PATH}/sales/category-list`,
//                         title: 'Categories',
//                         translateKey: 'nav.appsSales.categoryList',
//                         icon: '',
//                         type: NAV_ITEM_TYPE_ITEM,
//                         authority: [ADMIN, USER],
//                         subMenu: [],
//                     },
//                     {
//                         key: 'appsSales.AllProducts',
//                         path: `${APP_PREFIX_PATH}/sales/All-products`,
//                         title: 'Products',
//                         translateKey: 'nav.appsSales.allProducts',
//                         icon: '',
//                         type: NAV_ITEM_TYPE_ITEM,
//                         authority: [ADMIN, USER],
//                         subMenu: [],
//                     },
//                     // {
//                     //     key: 'appsSales.orderList',
//                     //     path: `${APP_PREFIX_PATH}/sales/order-list`,
//                     //     title: 'Order List',
//                     //     translateKey: 'nav.appsSales.orderList',
//                     //     icon: '',
//                     //     type: NAV_ITEM_TYPE_ITEM,
//                     //     authority: [ADMIN, USER],
//                     //     subMenu: [],
//                     // },
//                     // {
//                     //     key: 'appsSales.orderDetails',
//                     //     path: `${APP_PREFIX_PATH}/sales/order-details/95954`,
//                     //     title: 'Order Details',
//                     //     translateKey: 'nav.appsSales.orderDetails',
//                     //     icon: '',
//                     //     type: NAV_ITEM_TYPE_ITEM,
//                     //     authority: [ADMIN, USER],
//                     //     subMenu: [],
//                     // },
//                 ],
//             },
//             {
//                 // key: 'vendorManagement',
//                 key: 'apps.vendorManagement',
//                 path: `${APP_PREFIX_PATH}/vendor-management/VendorManagement`,
//                 title: 'Vendors',
//                 translateKey: 'Vendors',
//                 icon: 'crm',
//                 type: NAV_ITEM_TYPE_COLLAPSE,
//                 authority: [ADMIN],
//                 subMenu: [
//                     // {
//                     //     key: 'pendingVendors',
//                     //     path: `${APP_PREFIX_PATH}/vendor-management/PendingVendors`,
//                     //     title: 'Pending Vendors',
//                     //     translateKey: 'nav.vendorManagement.pendingVendors',
//                     //     icon: '',
//                     //     type: NAV_ITEM_TYPE_ITEM,
//                     //     authority: [ADMIN],
//                     //     subMenu: [],
//                     // },
//                     // {
//                     //     key: 'activeVendors',
//                     //     path: `${APP_PREFIX_PATH}/vendor-management/ActiveVendors`,
//                     //     title: 'Active Vendors',
//                     //     translateKey: 'nav.vendorManagement.activeVendors',
//                     //     icon: '',
//                     //     type: NAV_ITEM_TYPE_ITEM,
//                     //     authority: [ADMIN],
//                     //     subMenu: [],
//                     // },
//                     // {
//                     //     key: 'suspendedVendors',
//                     //     path: `${APP_PREFIX_PATH}/vendor-management/DeactivatedVendors`,
//                     //     title: 'Deactivated Vendors',
//                     //     translateKey: 'nav.vendorManagement.deactivatedVendors',
//                     //     icon: '',
//                     //     type: NAV_ITEM_TYPE_ITEM,
//                     //     authority: [ADMIN],
//                     //     subMenu: [],
//                     // },
//                 ],
//             },
//             {
//                 // key: 'productManagement',
//                 key: 'apps.productList',
//                 path: `${APP_PREFIX_PATH}/product-management/ListJewellery`,
//                 title: 'My Jewelleries',
//                 translateKey: 'My Jewelleries',
//                 icon: 'ring',
//                 type: NAV_ITEM_TYPE_COLLAPSE,
//                 authority: [VENDOR],
//                 subMenu: [],
//             },
//             {
//                 key: 'apps.coupons',
//                 path: `${APP_PREFIX_PATH}/manage-coupons`,
//                 title: 'Coupons',
//                 translateKey: 'Coupons',
//                 icon: 'coupons',
//                 type: NAV_ITEM_TYPE_COLLAPSE,
//                 authority: [VENDOR],
//                 subMenu: [],
//             },
//             {
//                 key: 'apps.vendorOrderManagement',
//                 path: `${APP_PREFIX_PATH}/vendor-orders/OrderManagement`,
//                 title: 'Orders',
//                 translateKey: 'Orders',
//                 icon: 'order',
//                 type: NAV_ITEM_TYPE_COLLAPSE,
//                 authority: [VENDOR],
//                 subMenu: [],
//             },
//             {
//                 key: 'orderList',
//                 path: `${APP_PREFIX_PATH}/sales/order-list`,
//                 title: 'Orders',
//                 // translateKey: 'nav.appsSales.orderList',
//                 icon: 'order',
//                 type: NAV_ITEM_TYPE_ITEM,
//                 authority: [ADMIN, USER],
//                 subMenu: [],
//             },

//             {
//                 // key: 'apps.account',
//                 // path: '',
//                 // title: 'Account',
//                 // translateKey: 'KYC Form',
//                 // icon: 'account',
//                 // type: NAV_ITEM_TYPE_COLLAPSE,
//                 // authority: [ADMIN, USER, VENDOR],
//                 // subMenu: [
//                 //     {
//                 key: 'appsAccount.settings',
//                 path: `${APP_PREFIX_PATH}/account/settings/profile`,
//                 title: 'Settings',
//                 // translateKey: 'nav.appsAccount.settings',
//                 // icon: '',
//                 icon: 'settings',
//                 type: NAV_ITEM_TYPE_ITEM,
//                 authority: [USER, VENDOR],
//                 subMenu: [],
//             },
//             // {
//             //     key: 'appsAccount.kycForm',
//             //     path: `${APP_PREFIX_PATH}/account/kyc-form`,
//             //     title: 'KYC Form',
//             //     translateKey: 'nav.appsAccount.kycForm',
//             //     icon: '',
//             //     type: NAV_ITEM_TYPE_ITEM,
//             //     authority: [USER],
//             //     subMenu: [],
//             // },
//             //     ],
//             // },
//         ],
//     },
// ]

// export default appsNavigationConfig

import { APP_PREFIX_PATH } from 'constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'
import { ADMIN, USER, VENDOR } from 'constants/roles.constant'

const appsNavigationConfig = [
    {
        key: 'apps',
        path: '',
        title: 'Dashboard',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER, VENDOR],
        subMenu: [
            // {
            // key: 'apps.sales',
            // path: '',
            // title: 'Sales',
            // translateKey: 'nav.appsSales.sales',
            // icon: 'sales',
            // type: NAV_ITEM_TYPE_COLLAPSE,
            // authority: [ADMIN, USER],
            // subMenu: [
            {
                key: 'appsSales.dashboard',
                path: `${APP_PREFIX_PATH}/sales/dashboard`,
                title: 'Overview',
                // title: 'Dashboard',
                // translateKey: 'nav.appsSales.dashboard',
                // icon: '',
                icon: 'overview',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, VENDOR, USER],
                subMenu: [],
            },
            {
                key: 'appsSales.categoryList',
                // path: `${APP_PREFIX_PATH}/sales/product-list`,
                path: `${APP_PREFIX_PATH}/sales/category-list`,
                title: 'Categories',
                // translateKey: 'nav.appsSales.categoryList',
                // icon: '',
                icon: 'categories',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'appsSales.AllProducts',
                path: `${APP_PREFIX_PATH}/sales/All-products`,
                title: 'Products',
                translateKey: 'nav.appsSales.allProducts',
                icon: 'ring',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            // ],
            // },
            {
                // key: 'vendorManagement',
                key: 'apps.vendorManagement',
                path: `${APP_PREFIX_PATH}/vendor-management/VendorManagement`,
                title: 'Vendors',
                translateKey: 'Vendors',
                icon: 'crm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                // key: 'productManagement',
                key: 'apps.productList',
                path: `${APP_PREFIX_PATH}/product-management/ListJewellery`,
                title: 'My Jewelleries',
                translateKey: 'My Jewelleries',
                icon: 'ring',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [VENDOR],
                subMenu: [],
            },
            {
                key: 'apps.coupons',
                path: `${APP_PREFIX_PATH}/manage-coupons`,
                title: 'Coupons',
                translateKey: 'Coupons',
                icon: 'coupons',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [VENDOR],
                subMenu: [],
            },
            {
                key: 'apps.vendorOrderManagement',
                path: `${APP_PREFIX_PATH}/vendor-orders/OrderManagement`,
                title: 'Orders',
                translateKey: 'Orders',
                icon: 'order',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [VENDOR],
                subMenu: [],
            },
            {
                key: 'orderList',
                path: `${APP_PREFIX_PATH}/sales/order-list`,
                title: 'Orders',
                // translateKey: 'nav.appsSales.orderList',
                icon: 'order',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'customers',
                path: `${APP_PREFIX_PATH}/sales/AllCustomers`,
                title: 'Customers',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'banner',
                path: `${APP_PREFIX_PATH}/manage-banner`,
                title: 'Banners',
                icon: 'banner',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'vendor.customers',
                path: `${APP_PREFIX_PATH}/vendor-customers`,
                title: 'Customers',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [VENDOR],
                subMenu: [],
            },
            {
                // key: 'apps.account',
                // path: '',
                // title: 'Account',
                // translateKey: 'KYC Form',
                // icon: 'account',
                // type: NAV_ITEM_TYPE_COLLAPSE,
                // authority: [ADMIN, USER, VENDOR],
                // subMenu: [
                //     {
                key: 'appsAccount.settings',
                path: `${APP_PREFIX_PATH}/account/settings/profile`,
                title: 'Settings',
                // translateKey: 'nav.appsAccount.settings',
                // icon: '',
                icon: 'settings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER, VENDOR],
                subMenu: [],
            },
            // {
            //     key: 'appsAccount.kycForm',
            //     path: `${APP_PREFIX_PATH}/account/kyc-form`,
            //     title: 'KYC Form',
            //     translateKey: 'nav.appsAccount.kycForm',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [USER],
            //     subMenu: [],
            // },
            //     ],
            // },
        ],
    },
]

export default appsNavigationConfig
